In [15]:
import sqlite3
import pandas as pd

pd.set_option('display.max_colwidth', None)

connection = sqlite3.connect("../data/sql-murder-mystery.db")
cursor = connection.cursor()

def sql_query(query):

    cursor.execute(query)
    ans = cursor.fetchall()
    names = [description[0] for description in cursor.description]

    return pd.DataFrame(ans, columns=names)

***QUERY 1 — Encontrar el informe del crimen***

In [16]:
query_1 = """
SELECT *
FROM crime_scene_report
WHERE date = 20180115
  AND type = 'murder'
  AND city = 'SQL City';
"""

sql_query(query_1)

,date,type,description,city
0,20180115,murder,"Security footage shows that there were 2 witnesses. The first witness lives at the last house on ""Northwestern Dr"". The second witness, named Annabel, lives somewhere on ""Franklin Ave"".",SQL City

***QUERY 2 — Encontrar al primer testigo***

In [17]:
query_2 = """
SELECT *
FROM person
WHERE address_street_name = 'Northwestern Dr'
ORDER BY address_number DESC
LIMIT 1;
"""

sql_query(query_2)

,id,name,license_id,address_number,address_street_name,ssn
0,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949

***QUERY 3 — Buscar la entrevista de Morty***

In [18]:
query_3 = """
SELECT *
FROM interview
WHERE person_id = 14887;
"""

sql_query(query_3)

,person_id,transcript
0,14887,"I heard a gunshot and then saw a man run out. He had a ""Get Fit Now Gym"" bag. The membership number on the bag started with ""48Z"". Only gold members have those bags. The man got into a car with a plate that included ""H42W""."

***QUERY 4 — Buscar socios del gimnasio***

In [19]:
query_4 = """
SELECT *
FROM get_fit_now_member
WHERE id LIKE '48Z%'
  AND membership_status = 'gold';
"""

sql_query(query_4)

      id  person_id           name  membership_start_date membership_status
0  48Z7A      28819   Joe Germuska               20160305              gold
1  48Z55      67318  Jeremy Bowers               20160101              gold

***QUERY 5 — Buscar el coche***

In [20]:
query_5 = """
SELECT *
FROM drivers_license
WHERE plate_number LIKE '%H42W%';
"""

sql_query(query_5)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,183779,21,65,blue,blonde,female,H42W0X,Toyota,Prius
1,423327,30,70,brown,brown,male,0H42W2,Chevrolet,Spark LS
2,664760,21,71,black,black,male,4H42WR,Nissan,Altima

***QUERY 6 — Cruzar sospechosos con sus carnets***

In [21]:
query_6 = """
SELECT
    person.id,
    person.name,
    person.license_id,
    drivers_license.plate_number,
    drivers_license.car_make,
    drivers_license.car_model
FROM person
JOIN drivers_license
    ON person.license_id = drivers_license.id
WHERE person.id IN (28819, 67318);
"""

sql_query(query_6)

      id           name  license_id plate_number   car_make car_model
0  67318  Jeremy Bowers      423327       0H42W2  Chevrolet  Spark LS

***QUERY 7 — Buscar a Annabel (segunda testigo)***

In [22]:
query_7 = """
SELECT *
FROM person
WHERE name LIKE 'Annabel%'
  AND address_street_name = 'Franklin Ave';
"""

sql_query(query_7)

,id,name,license_id,address_number,address_street_name,ssn
0,16371,Annabel Miller,490173,103,Franklin Ave,318771143

***QUERY 8 — Buscar la entrevista de Annabel***

In [23]:
query_8 = """
SELECT *
FROM interview
WHERE person_id = 16371;
"""

sql_query(query_8)

,person_id,transcript
0,16371,"I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th."

***QUERY 9 — Comprobar la entrada de Jeremy al gimnasio***

In [14]:
query_9 = """
SELECT *
FROM get_fit_now_check_in
WHERE membership_id = '48Z55'
  AND check_in_date = 20180109;
"""

sql_query(query_9)

  membership_id  check_in_date  check_in_time  check_out_time
0         48Z55       20180109           1530            1700

Jeremy Bowers estuvo en el gimnasio el 09/01/2018.

Esto confirma que Jeremy es el asesino